-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 21:32:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `ubicacion` VARCHAR(255) NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `fecha_nacimiento` DATE NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `id_sucursal` INT NULL,
  `Sucursal_id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_alumno`, `Sucursal_id_sucursal`),
  INDEX `fk_Alumno_Sucursal1_idx` (`Sucursal_id_sucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Sucursal1`
    FOREIGN KEY (`Sucursal_id_sucursal`)
    REFERENCES `mydb`.`Sucursal` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grado` (
  `id_grado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id_grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` TEXT NULL,
  `id_nivel` INT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `id_inscripcion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inscripcion` DATE NULL,
  `id_alumno` INT NULL,
  `id_curso` INT NULL,
  PRIMARY KEY (`id_inscripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion_has_Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion_has_Alumno` (
  `Inscripcion_id_inscripcion` INT NOT NULL,
  `Alumno_id_alumno` INT NOT NULL,
  PRIMARY KEY (`Inscripcion_id_inscripcion`, `Alumno_id_alumno`),
  INDEX `fk_Inscripcion_has_Alumno_Alumno1_idx` (`Alumno_id_alumno` ASC) VISIBLE,
  INDEX `fk_Inscripcion_has_Alumno_Inscripcion_idx` (`Inscripcion_id_inscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_Inscripcion_has_Alumno_Inscripcion`
    FOREIGN KEY (`Inscripcion_id_inscripcion`)
    REFERENCES `mydb`.`Inscripcion` (`id_inscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_id_alumno`)
    REFERENCES `mydb`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `id_nivel` INT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel_has_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel_has_Curso` (
  `Nivel_id_nivel` INT NOT NULL,
  `Curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`Nivel_id_nivel`, `Curso_id_curso`),
  INDEX `fk_Nivel_has_Curso_Curso1_idx` (`Curso_id_curso` ASC) VISIBLE,
  INDEX `fk_Nivel_has_Curso_Nivel1_idx` (`Nivel_id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_Nivel_has_Curso_Nivel1`
    FOREIGN KEY (`Nivel_id_nivel`)
    REFERENCES `mydb`.`Nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nivel_has_Curso_Curso1`
    FOREIGN KEY (`Curso_id_curso`)
    REFERENCES `mydb`.`Curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grado_has_Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grado_has_Nivel` (
  `Grado_id_grado` INT NOT NULL,
  `Nivel_id_nivel` INT NOT NULL,
  PRIMARY KEY (`Grado_id_grado`, `Nivel_id_nivel`),
  INDEX `fk_Grado_has_Nivel_Nivel1_idx` (`Nivel_id_nivel` ASC) VISIBLE,
  INDEX `fk_Grado_has_Nivel_Grado1_idx` (`Grado_id_grado` ASC) VISIBLE,
  CONSTRAINT `fk_Grado_has_Nivel_Grado1`
    FOREIGN KEY (`Grado_id_grado`)
    REFERENCES `mydb`.`Grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grado_has_Nivel_Nivel1`
    FOREIGN KEY (`Nivel_id_nivel`)
    REFERENCES `mydb`.`Nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
